backend:
  # Konfiguracja backendu Git-Gateway
  name: git-gateway
  branch: main # Upewnij się, że to jest nazwa Twojej głównej gałęzi Git
  squash_merges: repo
  auth_proxy: https://mobi-grooming.netlify.app/.netlify/identity

# Tryb publikacji: Umożliwia recenzję zmian przed publikacją (Draft -> In Review -> Ready -> Publish)
publish_mode: editorial_workflow

# Lokalizacja multimediów (obrazów)
# Wskazuje na folder w katalogu public, który jest dostępny w Netlify
media_folder: "frontend/public/pictures/uploads"  # Ścieżka względem katalogu głównego projektu
public_folder: "/pictures/uploads"       # Ścieżka publiczna (URL)

# --- KOLEKCJE TREŚCI ---
collections:

  # 1. KOLEKCJA JSON: Dostępność Kalendarza
  # Definiuje jeden plik do przechowywania listy dat niedostępności (wymagany przez komponent React)
  - name: "availability"
    label: "Kalendarz Dostępności"
    files:
      # ... reszta konfiguracji ...
      - label: "Lista Dat Niedostępności"
        name: "entries"
        widget: "list"
        fields:
          # ZMIANA: Zamiast jednego pola "date", tworzymy dwa pola na zakres
          - { label: "Data Początkowa", name: "date_start", widget: "datetime", format: "YYYY-MM-DD", time_format: false, required: true }
          - { label: "Data Końcowa (opcjonalnie, zostaw puste dla jednego dnia)", name: "date_end", widget: "datetime", format: "YYYY-MM-DD", time_format: false, required: false }
          - { label: "Notatka (np. Powód)", name: "note", widget: "string", required: false }
  # ... reszta konfiguracji ...

  # 2. KOLEKCJA MARKDOWN: Ogłoszenia i Komunikaty
  # Definiuje folder, w którym możesz tworzyć wiele wpisów (postów/komunikatów)
  - name: "announcements"
    label: "Ogłoszenia i Komunikaty"
    # To jest folder, w którym powstaną pliki .md (np. frontend/src/content/announcements/2025-10-18-urlop.md)
    folder: "frontend/src/content/announcements"
    create: true # Pozwala tworzyć nowe wpisy
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Format nazwy pliku
    sortable_fields: ['date', 'title']

    fields:
      - { label: "Tytuł Ogłoszenia", name: "title", widget: "string" }
      - { label: "Data Publikacji", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm" }
      - { label: "Treść Komunikatu", name: "body", widget: "markdown" } # Edytor WYSIWYG
      - { label: "Wyróżnione (Opcjonalnie)", name: "featured", widget: "boolean", default: false }