backend:
  # Konfiguracja backendu Git-Gateway
  name: git-gateway
  branch: main # Upewnij się, że to jest nazwa Twojej głównej gałęzi Git
  squash_merges: repo
  auth_proxy: https://mobi-grooming.netlify.app/.netlify/identity

# Tryb publikacji: Umożliwia recenzję zmian przed publikacją (Draft -> In Review -> Ready -> Publish)
publish_mode: editorial_workflow

# Lokalizacja multimediów (obrazów)
# Wskazuje na folder w katalogu public, który jest dostępny w Netlify
media_folder: "public/pictures/uploads"  # Ścieżka względem katalogu głównego projektu
public_folder: "/pictures/uploads"       # Ścieżka publiczna (URL)

# --- KOLEKCJE TREŚCI ---
collections:

  # 1. KOLEKCJA JSON: Dostępność Kalendarza
  # Definiuje jeden plik do przechowywania listy dat niedostępności (wymagany przez komponent React)
  - name: "availability"
    label: "Kalendarz Dostępności"
    files:
      - label: "Dni Niedostępne"
        name: "unavailable_dates"
        # Ścieżka, gdzie CMS zapisze dane: /public/data/unavailable.json
        file: "public/data/unavailable.json"
        format: "json" # Wymagany format: JSON
        fields:
          # Ponieważ CMS zawsze dodaje nadrzędny klucz dla listy, używamy "entries".
          # Pamiętaj o modyfikacji komponentu React, aby czytał json.entries!
          - label: "Lista Dat Niedostępności"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Data", name: "date", widget: "date", format: "YYYY-MM-DD", required: true }
              - { label: "Notatka (np. Powód)", name: "note", widget: "string", required: false }

  # 2. KOLEKCJA MARKDOWN: Ogłoszenia i Komunikaty
  # Definiuje folder, w którym możesz tworzyć wiele wpisów (postów/komunikatów)
  - name: "announcements"
    label: "Ogłoszenia i Komunikaty"
    # To jest folder, w którym powstaną pliki .md (np. frontend/src/content/announcements/2025-10-18-urlop.md)
    folder: "src/content/announcements"
    create: true # Pozwala tworzyć nowe wpisy
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Format nazwy pliku
    sortable_fields: ['date', 'title']

    fields:
      - { label: "Tytuł Ogłoszenia", name: "title", widget: "string" }
      - { label: "Data Publikacji", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm" }
      - { label: "Treść Komunikatu", name: "body", widget: "markdown" } # Edytor WYSIWYG
      - { label: "Wyróżnione (Opcjonalnie)", name: "featured", widget: "boolean", default: false }